### ISSUE TITLE
Build and test Elixir exercises with mix?

### ISSUE THREAD

**Issue by lpil** [exercism/xelixir#218]
Hello!

Mix is the official build tool for Elixir. Would it be better to use it to run the tests for the Elixir exercises? It's very unusual to manually import and compile code and to run ExUnit directly as we are currently doing.

**Comment by martinsvalin** [comment]
This confused me when I started the Elixir track. I expected to be able to run `mix test` and have the tests run. So I would +1 using mix. But then would you have one mix project per exercise? 

There may be a trade-off between being familiar and idiomatic to existing language users, and having more structure and complexity for a total language beginner. Having two files `the_exercise.exs` and `the_exercise_test.exs` is undoubtedly simpler than having `lib/the_exercise.ex`, `test/the_exercice_test.exs`, a `.mix.exs` file, etc. Do we keep `config/config.exs`? Do we keep `test/test_helper.exs`?

I think it's a Very Good Thing™ that mix encourages a best-practice project structure, and it's something that's valuable to learn early on when learning Elixir. Overall, I think it'd be good to expose beginners to this as well, even if it does come across as overkill. There's a stronger culture among Elixir programmers to abide by this project structure than in most languages, I think.

Maybe the `hello_world` exercise's README could expand a bit, explaining the context and purpose of this directory structure.

**Comment by parkerl** [comment]
We'd love to see a PR if you feel the documentation around running the exercises could be better. 

The idea of using mix for each exercise has been discussed previously. The general feeling has been that mix is unnecessary because the exercises are very simple scripts and not full blown projects. As @martinsvalin points out, each exercise would need to become a full blown mix project with more files needed per exercise. The added burden on maintainers and contributors outweighs the small amount of convenience that running tests with mix provides. 

I would also add that, personally, I think there is value in demonstrating alternative methods of running Elixir code. 

Thanks for raising the issue.

**Comment by lpil** [comment]
I feel I should stress that even with scripts it's still the norm to use mix. This is the only project I've encountered that doesn't use mix.

> each exercise would need to become a full blown mix project with more files needed per exercise

Converting to a mix project would require adding two files with 12 longer between them. We could also remove the highly unidiomatic boilerplate from the tests.

There would be less burden on maintainers as there's no test running to manually manage, and there would be no need to explain the custom setup.
