### ISSUE TITLE
nucleotide: raising errors?

### ISSUE THREAD

**Issue by Trevoke** [exercism/xelixir#224]
It's not very Elixir-ish to raise an error. The preferred pattern is to return a tuple like `{:error, :invalid_strand}`. Is this only there as a learning tool to learn how to raise errors?

[Edit: adding link to  exercise https://github.com/exercism/xelixir/tree/master/exercises/nucleotide-count ]

**Comment by martinsvalin** [comment]
I would say this exercise is about learning to count frequencies, not raising errors, and it would be improved by showing more idiomatic error handling.

**Comment by martinsvalin** [comment]
OTOH, maybe it isn't unidiomatic (sorry about the double negation) to raise ArgumentError on bad input. Plenty of Elixir stdlib functions will do so, for instance `URI.encode_query(foo: 'bar')` will raise because the value is a charlist. Most of the functions that raise ArgumentError are ones that end with `!`, though, with a non-bang counterpart that returns an error tuple.

I don't think it's cut-and-dry. The `{:ok, value} | {:error, reason}` idiom is very appropriate when your function can fail on normal, expected input, but even in a situation where the input is of the wrong type, it could be appropriate to return an error tuple. It let's the user of the function determine whether to fail immediately or not, without cumbersome try-rescue blocks.

I _think_ the community prefers error tuples to raising, and if others agree, I think it would be more valuable to update this exercise, and educate about the idiom.

**Comment by Trevoke** [comment]
I think (and here, as a relative beginner to Elixir, I'm uncertain) that the difference here is in "Elixir stdlib". Something like this `DNA` module could well be a separate system, running as a process in a different supervisor tree. Do we really want it to throw an error?

**Comment by lpil** [comment]
I agree that we should not be manually throwing an error. We could either return an error tuple, or encourage offensive programming by having the user creating a function that does not have function clauses defined for non-valid characters.

The example for this exercise is also not great. It iterates over the list twice when it only needs to iterate once.

**Comment by parkerl** [comment]
Thanks for raising the issue. This is a good discussion. Currently we have exercises that use both :error tuples and `raise`. I think it is a little tricky to pick one over another in Exercism as these are small scripts used for practice. The choice of error mechanism is usually made in the broader context of a system. IMHO it is a matter of communication. Elixir does have a culture of trying to provide useful error messages. An :error tuple typically communicates that we know a function can fail and it is expected. Raising an exception indicates that we don't expect the function to fail but something unexpected might happen. It is difficult to know which would be appropriate for nucleotide count IRL. AFAIK when this exercise was implemented, the decision was made to raise an  `ArgumentError` to communicate that bad input is not expected. As @martinsvalin points out, Elixir libraries also go both ways (thanks for doing that research!!!).

All that said, I think there is value in submitters learning to work with both. However, we would not reject a PR on this out of hand. 

@lpil We'd be happy to see a PR improving the example. Just FYI, we don't require that the example be a "gold standard" for implementing the exercise. It need only test the tests by making them pass.

**Comment by devonestes** [comment]
My thinking on this is that we should have at least one or two exercises that do show how to use `raise` since that's a valid concept and is used throughout the standard library. Picking up off of @martinsvalin's observation, I wouldn't be opposed to creating both a version that returns the error tuple _and_ a version that raises the `ArgumentError`, so we could write tests for a `count` function that returns a tuple, and a `count!` function that raises the error. I think that's a good pattern, and is widely used throughout Elixir, so it wouldn't be a bad thing to teach here.

**Comment by lpil** [comment]
That sounds great to me!
