### ISSUE TITLE
Ensure compatibility with Elixir 1.4.2 and make that the default target

### ISSUE THREAD

**Issue by parkerl** [exercism/xelixir#288]
- [ ] Make dialyzer happy
- [ ] Update all documentation references from 1.3.2 to 1.4.2

**Comment by bunnymatic** [comment]
I'm not sure what this ticket represents exactly but recently, while trying to do the `meetup` exercise, I found that I was back on Elixir 1.2 and unable to get to the Date module functions.  There is no indication in the exercise or on the site (that I was able to find) that says what version of Elixir is required.  Should that work be included here?  Or should I file a ticket against the site to specify required language versions for the overall exercises? 

Before Upgrade:
```
meetup $ iex
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.2.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Date.new 2016, 01, 01
** (UndefinedFunctionError) undefined function Date.new/3 (module Date is not available)
    Date.new(2016, 1, 1)
```

After
```
meetup $ iex
Erlang/OTP 19 [erts-8.2] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Interactive Elixir (1.4.0) - press Ctrl+C to exit (type h() ENTER for help)
iex(1)> Date.new 2016, 01, 01
{:ok, ~D[2016-01-01]}

**Comment by martinsvalin** [comment]
@bunnymatic - The exercises as such should not require a recent version of Elixir. Anyone implementing the Elixir track should be able to use any Elixir version likely to still be in use. Elixir 1.3 (where the Date struct was introduced) is only a little over half a year old.

The tests for the Meetup exercise expect Erlang date tuples (`{year, month, day}`) to be returned. You are of course welcome to implement the exercise using the new Date struct, but the exercise as such should not force this. (Btw, feel free to rewrite your `meetup_test.exs` to expect Date structs if you do. It's perfectly fine to update the return type if you like. Returning a Date struct would probably be regarded as more idiomatic by now.)

This issue is to update the version of Elixir used when running the test suite on Travis-CI when exercises are added or updated. All exercises should work well for the latest Elixir version, without emitting deprecation warnings.

**Comment by bunnymatic** [comment]
got it.  I guess *I* required a new version of elixir because I was on 1.2.
Thanks for the info

**Comment by ckhrysze** [comment]
If the exercises do not require the latest versions of elixir, should this ticket remain open?

**Comment by parkerl** [comment]
Thanks @ckhrysze 

We don't require 1.4 but we need to support it. It needs to become our default version for the track as a whole.
